#!/bin/bash
if [[ "$1" == "" ]] ; then
  echo "Please specify a build type to deploy. ( Release | Debug )"
elif ! [[ -d bin/$1 ]] ; then
  echo "Build type \"$1\" does not exist. Please specify a build type to deploy. ( Release | Debug )"
else
  cp hasher ~/bin
  cp bin/$1/Hasher.exe ~/bin/PC
  cp bin/$1/Hasher.exe.mdb ~/bin/PC
fi
